### ISSUE TITLE
getOutDir() does not respect foundry.toml configuration for the output directory

### ISSUE THREAD

**Issue by RickVM** [OpenZeppelin/openzeppelin-foundry-upgrades#10]
We use the foundry.toml to configure our output directory, it doesn't seem to be picked up though as calling Upgrades.upgradeProxy fails because it is trying to access something from the path `out/` whereas we use `dist/`

Part of our foundry.toml
```toml
[profile.default]
out = './dist'
```

This seems to be the bad boy in src/internal/Utils.sol
```solidity
    function getOutDir() internal returns (string memory) {
        Vm vm = Vm(CHEATCODE_ADDRESS);

        string memory defaultOutDir = "out";
        return vm.envOr("FOUNDRY_OUT", defaultOutDir);
    }
```

**Comment by ericglau** [comment]
Can you set the `FOUNDRY_OUT` environment variable to `dist`, for example in your `.env` file?  This is something we'll add to the documentation.

We currently don't have a way to retrieve the setting from foundry.toml, and I don't think Foundry exposes this.  Parsing the file from the library would not be reliable because the setting could possibly in a different profile other than `profile.default`, and would depend on which profile you are using.

**Comment by RickVM** [comment]
Ah ok, yeah I already fixed it by setting it in the env but figured this would be nice if doable. Thanks
