### ISSUE TITLE
Remove NodeJS dependencies

### ISSUE THREAD

**Issue by Magicking** [OpenZeppelin/openzeppelin-foundry-upgrades#11]
This plugin is great to help improve developer safety while doing upgrades but,

It require the addition of a whole another language (Javascript with NodeJS) while it seems that the necessity for this is solely to parse JSON data (e.g: build info) while Foundry is fully [equipped](https://book.getfoundry.sh/cheatcodes/parse-json) to do so.

Could you remove this unwanted dependency ?

From a PoV of a dev. that got rid of hardhat and the whole JS ecosystem to dive in foundry to have a simple dev toolkit, this is a step backward.

**Comment by ericglau** [comment]
Thanks for the feedback.

The requirement for NodeJS is mainly for performing validations as described in [Before Running](https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades?tab=readme-ov-file#before-running).  This includes checking for upgrade safety and storage layout compatibility.  We recommend having NodeJS available so that these can be run during function calls to this library to help protect from unsafe upgrades.

If you have a separate step (whether manually or automatically) in your process to perform the same types of checks before deployment, then these validations can be disabled according to the linked documentation.  Then you can run deploy or upgrade functions without NodeJS.

We currently do not plan to remove this dependency, because of its importance towards security.  While Foundry can parse JSON as you mentioned, the [validation logic](https://github.com/OpenZeppelin/openzeppelin-upgrades/tree/master/packages/core/src) that we use is quite complex and it would be a very large effort to reimplement the entire validation code in Solidity.

**Comment by Magicking** [comment]
It seems that introducing an attack surface (NodeJS, commonly known as the supply-chain-attack-of-hell) for a security plugin is a bad idea, maybe considering a bounty for this harduous task would be worth the effort of improving the security of your users.

**Comment by ericglau** [comment]
I understand the motivation.  However, due to the complexity of the validations that are currently implemented for NodeJS, we believe it would be less secure to reimplement these in a different language and maintain two separate implementations.  For example, if the reimplementation is less complete in terms of features or logic, certain scenarios may be missed, it could have restrictions, or it may lead to a poorer user experience.  Dual maintenance in different languages may also lead to divergence resulting in the above.

Here are some examples of the validations that are performed:
- [Checks for constructors and unsafe opcodes](https://docs.openzeppelin.com/upgrades-plugins/1.x/faq#what-does-it-mean-for-a-contract-to-be-upgrade-safe)
- [Checks for immutable variables](https://docs.openzeppelin.com/upgrades-plugins/1.x/faq#why-cant-i-use-immutable-variables)
- [Checks for an upgrade function in UUPS implementations](https://docs.openzeppelin.com/upgrades-plugins/1.x/faq#why-public-upgradeto)
- [Handling variable renamings](https://docs.openzeppelin.com/upgrades-plugins/1.x/faq#how-to-rename)
- [Storage layout comparisons](https://docs.openzeppelin.com/upgrades-plugins/1.x/writing-upgradeable#modifying-your-contracts) and useful error reports if there are layout conflicts.
- [Supporting use of storage gaps](https://docs.openzeppelin.com/upgrades-plugins/1.x/writing-upgradeable#storage-gaps) and useful error reports on incorrect usage.
- [Supporting use of namespaced storage](https://docs.openzeppelin.com/upgrades-plugins/1.x/writing-upgradeable#namespaced-storage-layout) and useful error reports for incorrect usage.

If supply chain is a concern, a possible approach may be to use a lockfile and preinstall the `@openzeppelin/upgrades-core` npm package, which will cause the library to use the preinstalled package.
