### ISSUE TITLE
Forge script returns error: Could not open compiler cache after upgrades plugin

### ISSUE THREAD

**Issue by cemleme** [OpenZeppelin/openzeppelin-foundry-upgrades#31]
I am able to run all my tests through 

`forge clean && forge build && forge test --ffi`

I can run forge script without the Upgrades through forge script DeployContracts ..... etc

but when I use (of course also tested with other networks instead of local)

`forge clean && forge build && forge script DeployContracts --rpc-url http://127.0.0.1:7545 --private-key 0x... --broadcast --ffi --sender 0x... --force
`
or
` forge script DeployContracts --rpc-url http://127.0.0.1:7545 --private-key 0x... --broadcast --ffi --sender 0x... 
`
or
`forge script DeployContracts --rpc-url http://127.0.0.1:7545 --private-key 0x... --broadcast --ffi --sender 0x... --force
`

it returns an error of 

```
Compiler run successful!
Error: 
Could not open compiler cache

Context:
- "/Users/ce/Developer/ce/dev/repo/foundry/cache/solidity-files-cache.json": No such file or directory (os error 2)
```

I also tested this on a fresh upgrades repo trying to run Counter.s script and still got the same error so might be related to my setup?

macOS
node: v20.10.0
forge 0.2.0 (42da942 2024-03-16T00:15:49.251465000Z)
"@openzeppelin/upgrades-core": "^1.32.5"

**Comment by ericglau** [comment]
This might be an environment issue since the plugin does not read the `solidity-files-cache.json` directly.

Can you try the following to get a new repo, and see if it works on your environment?
1. Go to https://deploy-preview-346--openzeppelin-contracts-wizard.netlify.app/ -- this is a preview for https://github.com/OpenZeppelin/contracts-wizard/pull/346, which lets you download a package which has the Foundry Upgrades plugin enabled.
2. Enable Upgradeability on the left side
3. Click Download -> Development Package (Foundry)
4. Unzip the package and follow the steps in the readme

**Comment by ericglau** [comment]
Closing as this looks like an environment issue. Feel free to comment or reopen if needed.
